config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'search/search'
  devise_for :users
  root 'homes#about'
  get 'top' => 'homes#top'
  get 'user/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'user/withdraw' => 'users#withdraw'
  get '/search' => 'search#search'

  resources :users, only: [:show, :edit, :update, :index, :unsubscribe, :withdraw] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'favorites' => 'favorites#favorites', as: 'favorites'
  end

  resources :photos, only: [:show, :edit, :update, :index, :destroy, :new, :create] do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
>>>>>>> origin/main
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
  validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回お気に入りさせない
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
	belongs_to :photo
	validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回いいねさせない
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, class_name: 'User'
  attachment :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image,presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
      Photo.where('title LIKE(?) OR body LIKE(?) OR place LIKE(?)', '%'+content+'%', '%'+content+'%', '%'+content+'%')
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationshios, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #自分がフォローされる側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #自分がフォローする側
  has_many :followers, through: :reverse_of_relationshios, source: :follower #自分をフォローしてるユーザー
  has_many :followings, through: :relationships, source: :followed #自分がフォローしてるユーザー

  validates :name, presence: true
  validates :partner_name, presence: true
  validates :couple_name, presence: true
  validates :email, presence: true
  validates :anniversary, presence: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
      User.where('couple_name LIKE ?', '%'+content+'%')
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    if @photo.user_id != current_user.id
      @favorite = @photo.favorites.new(user_id: current_user.id)
      @favorite.save
    end
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    favorite = @photo.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

  def favorites
    favorites = Favorite.where(user_id: current_user.id).pluck(:photo_id) #ログイン中のユーザーのお気に入りのphoto_idカラムを取得
    @favorite = Photo.find(favorites)  #photosテーブルから、お気に入り登録済みのレコードを取得
    @photos = Photo.page(params[:page]).reverse_order
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @photos = Photo.limit(5).order(" created_at DESC ")
    @users = User.limit(5)
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.new(photo_id: @photo.id)
    like.save
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.find_by(photo_id: @photo.id)
    like.destroy
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def show
    @photo = Photo.find(params[:id])
    @user = @photo.user
    @comment = Comment.new
  end

  def new
    @photo = Photo.new
    @user = current_user
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    @user = current_user
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    @user = current_user
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photo_path(@photo.id)
    else
      render :edit
    end
  end

  def index
    @photos = Photo.page(params[:page]).reverse_order
    @user = current_user
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :body, :image, :place, :name)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method).page(params[:page]).reverse_order
    else
      @records = Photo.search_for(@content, @method).page(params[:page]).reverse_order
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @ausers = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :partner_name, :anniversary, :couple_name, :email, :is_deleted, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<%# if photo.favorited_by?(current_user) %>
  <%#= link_to photo_favorites_path(photo), method: :delete, class: "fas fa-bookmark heart_red" %>
<%# else %>
  <%#= link_to photo_favorites_path(photo), method: :post, class: "fas fa-bookmark heart_blue" %>
<%# end %>

<% if !Favorite.exists?(user_id: current_user.id, photo_id: photo.id) %>
  <%= link_to photo_favorites_path(photo), method: :post, remote: true do %>
    <i class="far fa-bookmark"></i>
  <% end %>
<% else %>
  <%= link_to photo_favorites_path(photo), method: :delete, remote: true do %>
    <i class="fas fa-bookmark"></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_<%= @photo.id %> ").html("<%= j(render 'favorites/favorite', photo: @photo) %>");

app/views/favorites/destroy.js.erb
$("#favorite_<%= @photo.id %> ").html("<%= j(render 'favorites/favorite', photo: @photo) %>");

app/views/favorites/favorites.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-xs-12 col-lg-8 col-xl-9 mx-auto">
      <h5 class="mt-5 mt-lg-0 text-center">Favorites</h5>
        <div class="photo_view">
          <div class="d-flex flex-wrap bd-highlight">
            <% if @favorite.present? %>
              <% @favorite.each do |photo| %>
                <div class="card mr-2 mt-2" style="width: 12rem;">
                  <div class="p-1 flex-fill bd-highlight">
                    <%= link_to photo_path(photo.id) do %>
                      <%= attachment_image_tag photo, :image,:fill,170,140, class: "card-img-top rounded" %>
                    <% end %>
                  </div>
                  <div class="card-body">
                    <p class="card-title">
                      <%= link_to user_path(photo.user) do %>
                        <%= photo.user.couple_name %>
                      <% end %>
                    </p>
                    <p class="card-text">
                      <%= photo.title %>
                    </p>
                  </div>
                </div>
              <% end %>

            <% else %>
              <p class="mt-3 mx-auto text-center">お気に入りはありません</p>
            <% end %>
          </div>
        </div>
        <div class="col-xs-12 col-lg-8 col-xl-9 mx-auto mt-5"><%= paginate @photos %></div>
    </div>
  </div>
</div>