config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'search/search'
  devise_for :users
  root 'homes#about'
  get 'top' => 'homes#top'
  get 'user/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'user/withdraw' => 'users#withdraw'
  get '/search' => 'search#search'

  resources :users, only: [:show, :edit, :update, :index, :unsubscribe, :withdraw] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'favorites' => 'favorites#favorites', as: 'favorites'
  end

  resources :photos, only: [:show, :edit, :update, :index, :destroy, :new, :create] do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
>>>>>>> origin/main
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
  validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回お気に入りさせない
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
	belongs_to :photo
	validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回いいねさせない
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, class_name: 'User'
  attachment :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image,presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
      Photo.where('title LIKE(?) OR body LIKE(?) OR place LIKE(?)', '%'+content+'%', '%'+content+'%', '%'+content+'%')
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationshios, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #自分がフォローされる側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #自分がフォローする側
  has_many :followers, through: :reverse_of_relationshios, source: :follower #自分をフォローしてるユーザー
  has_many :followings, through: :relationships, source: :followed #自分がフォローしてるユーザー

  validates :name, presence: true
  validates :partner_name, presence: true
  validates :couple_name, presence: true
  validates :email, presence: true
  validates :anniversary, presence: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
      User.where('couple_name LIKE ?', '%'+content+'%')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.new(comment_params)
    @comment.photo_id = @photo.id
    @comment.user_id = current_user.id
    unless @comment.save
      render 'error'
    end
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    comment = @photo.comments.find(params[:id])
    comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :photo_id, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @photos = Photo.limit(5).order(" created_at DESC ")
    @users = User.limit(5)
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.new(photo_id: @photo.id)
    like.save
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.find_by(photo_id: @photo.id)
    like.destroy
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def show
    @photo = Photo.find(params[:id])
    @user = @photo.user
    @comment = Comment.new
  end

  def new
    @photo = Photo.new
    @user = current_user
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    @user = current_user
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    @user = current_user
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photo_path(@photo.id)
    else
      render :edit
    end
  end

  def index
    @photos = Photo.page(params[:page]).reverse_order
    @user = current_user
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :body, :image, :place, :name)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method).page(params[:page]).reverse_order
    else
      @records = Photo.search_for(@content, @method).page(params[:page]).reverse_order
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @ausers = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :partner_name, :anniversary, :couple_name, :email, :is_deleted, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="new-comment" data-turbolinks='false'>
  <%= form_with model:[photo,comment], remote: true do |f| %>
    <%= f.text_area :comment, size:"90x5", placeholder: "Please enter your comments",class:"comment-form", 'data-turbolinks': false %>
    <div class="form_btn offset-11" data-turbolinks='false'>
    <%= f.submit "Post",class:"btn btn-border", 'data-turbolinks': false %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<div class="comment" data-turbolinks='false'>
  <% photo.comments.each do |comment| %>
    <p>
      <%= link_to user_path(comment.user),class: "user_#{comment.user.id}" do %>
        <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50",class: "rounded-circle" %>
        <%= comment.user.couple_name %>
      <% end %>
      
      <%= comment.created_at.strftime('%Y/%m/%d') %>
      
      <% if current_user == comment.user %>
        <%= link_to '', photo_comment_path(comment.photo_id, comment.id), method: :delete, remote: true,class:"fas fa-trash" %>
    <% end %>
    </p>
    <p><%= comment.comment %></p>
    
</div>
<% end %>

app/views/comments/create.js.erb
$("#comment_<%= @photo.id %> .comments-count").html("<%= @photo.comments.count %>コメント");
$(".comments").html("<%= j(render 'comments/index', photo: @photo) %>");
$("#comment_comment").val("");

app/views/comments/destroy.js.erb
$("#comment_<%= @photo.id %> .comments-count").html("<%= @photo.comments.count %>コメント");
$(".comments").html("<%= j(render 'comments/index', photo: @photo) %>");
$("#comment_comment").val("");

app/views/comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/errors', obj: @comment) %>");

app/views/likes/_like.html.erb
<% if photo.liked_by?(current_user) %>
  <%= link_to photo.likes.count, photo_likes_path(photo), method: :delete,remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to photo.likes.count, photo_likes_path(photo), method: :post,remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/likes/create.js.erb
$("#like_<%= @photo.id %> ").html("<%= j(render 'likes/like', photo: @photo) %>");

app/views/likes/destroy.js.erb
$("#like_<%= @photo.id %> ").html("<%= j(render 'likes/like', photo: @photo) %>");

app/views/photos/_comment.html.erb
<div class="comment">
  <p><%= @photo.comments.count %></p>
  <% @photo.comments.each do |comment| %>
    <p>
      <%= link_to user_path(comment.user),class: "user_#{comment.user.id}" do %>
        <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
        <%= comment.user.couple_name %>
        <%= comment.created_at.strftime('%Y/%m/%d') %>
      <% end %>
    </p>
    <p><%= comment.comment %></p>
    <% if current_user == comment.user %>
      <p><%= link_to 'Destroy', photo_comment_path(comment.photo_id, comment.id), method: :delete %></p>
    <% end %>
</div>
<% end %>
<div class="new-comment">
  <%= form_with(model:[@photo,@comment], local: true)do |f| %>
    <%= f.text_area :comment, size:"90x5", placeholder: "Please enter your comments" %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/photos/_index.html.erb
<div class="photo_view">
  <div class="d-flex flex-wrap bd-highlight">
    <% photos.each do |photo| %>
      <% unless photo.user.is_deleted == true %>
        <div class="card mr-2 mt-2" style="width: 12rem;">
          <div class="p-1 flex-fill bd-highlight" >
            <%= link_to photo_path(photo.id) do%>
              <%= attachment_image_tag photo, :image,:fill,170,140, class: "card-img-top rounded", 'data-turbolinks': false  %>
            <% end %>
          </div>
          <div class="card-body">
            <p class="card-title">
              <%= link_to user_path(photo.user) do %>
                <%= photo.user.couple_name %>
              <% end %>
              | <i class="fas fa-heart heart_red"><%= photo.likes.count %></i>
            </p>
            <p class="card-text"><%= photo.title %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="container mb-5">
 <div class="row d-flex justify-content-center">
  <h2>Edit Post</h2>
  <%= render 'layouts/errors', obj: @photo %>
 </div>
  <%= form_with model: @photo, local:true do |f| %>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="col-6 col-lg-5 text-center">
     <%= attachment_image_tag @photo, :image, width: "70%",height: "auto", fallback: "no_image.jpg" %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <%= f.text_field :title, autofocus: true, class:"input-text form-js-input",placeholder: "Title" %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
   <div class="form_line col-6 col-lg-5">
    <li class="form_title">Name</li>
    <ul class="radio_conntent ml-auto d-flex justify-content-center ">
     <li class="radio_text">
     <%= f.radio_button :name, @user.name, checked: true %>
     <%= f.label :name,@user.name %>
     </li>
     <li class="radio_text">
     <%= f.radio_button :name, @user.partner_name, checked: true %>
     <%= f.label :name,@user.partner_name %>
     </li>
     <li class="radio_text">
     <%= f.radio_button :name, @user.name+'+'+@user.partner_name, checked: true %>
     <%= f.label :name,@user.name+'+'+@user.partner_name %>
     </li>
    </ul>
   </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <%= f.text_field :place, autofocus: true, class:"input-text form-js-input",placeholder: "Place" %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_box col-6 col-lg-5">
     <%= f.text_area :body, autofocus: true, class:"input-text form-js-input",placeholder: "Comment" %>
    </div>
   </div>
   <div class="form_btn offset-md-8 mt-5">
    <%= f.submit 'Update',class:"btn btn-border" %>
   </div>
  <% end %>
 </div>
</div>

app/views/photos/index.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-xs-12 col-lg-8 col-xl-9 mx-auto">
        <h5 class="mt-5 mt-lg-0 text-center">New Posts</h5>
        <%= render 'index', photos: @photos %>
    </div>
  </div>
  <%= paginate @photos %>
</div>

app/views/photos/new.html.erb
<div class="container mb-5">
 <div class="row d-flex justify-content-center">
  <h2>Post our love</h2>
 </div>
 <div class="row d-flex justify-content-center mt-2">
  <%= render 'layouts/errors', obj: @photo %>
 </div>


  <%= form_with model: @photo, local:true do |f| %>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <%= f.attachment_field :image %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <%= f.text_field :title, autofocus: true, class:"input-text form-js-input",placeholder: "Title" %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <li class="form_title">Name</li>
     <ul class="radio_conntent ml-auto d-flex justify-content-center ">
      <li class="radio_text">
      <%= f.radio_button :name, @user.name, checked: true %>
      <%= f.label :name,@user.name %>
      </li>
      <li class="radio_text">
      <%= f.radio_button :name, @user.partner_name, checked: true %>
      <%= f.label :name,@user.partner_name %>
      </li>
      <li class="radio_text">
      <%= f.radio_button :name, @user.name+'+'+@user.partner_name, checked: true %>
      <%= f.label :name,@user.name+'+'+@user.partner_name %>
      </li>
     </ul>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_line col-6 col-lg-5">
     <%= f.text_field :place, autofocus: true, class:"input-text form-js-input",placeholder: "Place" %>
    </div>
   </div>
   <div class="row mt-5 d-flex justify-content-center">
    <div class="form_box col-6 col-lg-5">
     <%= f.text_area :body, autofocus: true, class:"input-text form-js-input",placeholder: "Comment" %>
    </div>
   </div>
   <div class="form_btn offset-md-8 mt-5">
    <%= f.submit 'Post',class:"btn btn-border" %>
   </div>
  <% end %>
 </div>
</div>

app/views/photos/show.html.erb
<div class="container px-5 px-sm-0 mb-5 mt-4">
  <div class="row">
    <div class='col-md-3'>
      <%= render 'users/info', user: @photo.user %>
    </div>
    <div class="col-md-8">
      <div class="row ml-3">
        <%= attachment_image_tag @photo, :image,class:"card-img-top"; %>

        <div class="et-btn offset-11">
        <% if @photo.user == current_user %>
          <span class="mr-3"><%= link_to "", edit_photo_path(@photo.id),class:"fas fa-pen-square" %></span>
          <span><%= link_to "", photo_path(@photo), method: :delete,class:"fas fa-trash" %></span>
        <% else %>
          <div class="mb-3"></div>
        <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="card-body pt-0">
          <div class="card-title">
            <span data-turbolinks='false'>
              <%= link_to user_path(@photo.user) do %>
                <%= @photo.user.couple_name %>
              <% end %>
            </span>
            <span id="like_<%= @photo.id %>"><%= render "likes/like", photo: @photo %></span>
            <span id="favorite_<%= @photo.id %>"><%= render "favorites/favorite", photo: @photo %></span>
          </div>
          <p class="card-text"><%= @photo.title %></p>
          <p class="card-text"><%= @photo.body %></p>
          <p class="card-text"><%= @photo.name %></p>
          <p class="card-text"><%= @photo.created_at.strftime('%Y/%m/%d') %></p>
        </div>

        <div class="row ml-3 mt-4 mb-5">
          <div class="comments" data-turbolinks='false'><%= render 'comments/index', photo: @photo %></div>
          <div id="comments_error" data-turbolinks='false'><%= render 'layouts/errors', obj: @comment %></div>
          <div class="mt-3" data-turbolinks='false'><%= render 'comments/comment',photo: @photo, comment: @comment %></div>
        </div>
      </div>
    </div>

  </div>
</div>