config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'search/search'
  devise_for :users
  root 'homes#about'
  get 'top' => 'homes#top'
  get 'user/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'user/withdraw' => 'users#withdraw'
  get '/search' => 'search#search'

  resources :users, only: [:show, :edit, :update, :index, :unsubscribe, :withdraw] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'favorites' => 'favorites#favorites', as: 'favorites'
  end

  resources :photos, only: [:show, :edit, :update, :index, :destroy, :new, :create] do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
>>>>>>> origin/main
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationshios, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #自分がフォローされる側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #自分がフォローする側
  has_many :followers, through: :reverse_of_relationshios, source: :follower #自分をフォローしてるユーザー
  has_many :followings, through: :relationships, source: :followed #自分がフォローしてるユーザー

  validates :name, presence: true
  validates :partner_name, presence: true
  validates :couple_name, presence: true
  validates :email, presence: true
  validates :anniversary, presence: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
      User.where('couple_name LIKE ?', '%'+content+'%')
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if ((@user.valid_password?(params[:user][:password])) && (@user.active_for_authentication? == false))
        redirect_to new_user_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @ausers = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :partner_name, :anniversary, :couple_name, :email, :is_deleted, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
  <% unless user.is_deleted == true %>
    <div class="col-md-2.5 ml-2 mr-2">
      <div class="row mt-3">
        <div class="col-md-12 text-left">
          <%= attachment_image_tag(user, :profile_image,:fill, 150, 150, fallback: "no_image.jpg", size: "150x150")%>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-left" style="margin-top: 20px;">
          <%= link_to user.couple_name,user_path(user.id), 'data-turbolinks': false %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_info.html.erb
<div class ="info-table">
  <div class ="info-main text-center mt-2"><h5>- info -</h5></div>
  <div class ="info-img text-center mb-1"><%= attachment_image_tag(user, :profile_image,:fill, 100, 100,fallback: "no_image.jpg", size: "100x100")%></div>

  <table class="table table-borderless">
    <tr>
      <th><%= user.name %></th>
      <th><%= user.partner_name %></th>
    </tr>
    <tr>
      <th><%= user.anniversary %></th>
    </tr>
    <tr>
      <th><%= user.couple_name %></th>
    </tr>
    <tr>
      <th>Follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>Followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </table>

  <div class='info-btn text-right mr-2 mb-3'>
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class: "btn-flat-border-filled" %>
      <% else %>
        <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn-flat-border" %>
      <% end %>
    <% else %>
      <div>
        <%= link_to '', edit_user_path(user),class: "fas fa-cog nav-link text-danger edit_user_#{user.id}" %>
        <%= link_to '', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-xs-6 mx-auto"><h4>Edit Profile</h4></div>
  </div>
  <div class="row">
    <div class="col-xs-6 mx-auto"><%= render 'layouts/errors', obj: @user %></div>
  </div>
  
  <%= form_with model: @user, local:true do |f| %>

    <div class="row mt-5 d-flex justify-content-center">
      <div class="col-6 col-lg-5 text-center">
        <%= attachment_image_tag @user, :profile_image, :fill,200,200, fallback: "no_image.jpg", size: "200x200"%>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="form_line col-6 col-lg-5">
        <%= f.label "Profile Image" %><br />
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="form_line col-6 col-lg-5">
        <%= f.label "Cp name" %><br />
        <%= f.text_field :couple_name, autofocus: true, class:"input-text form-js-input",placeholder: "tonecp-1201"  %>
      </div>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="form_line col-6 col-lg-5">
        <%= f.label "Name1" %><br />
        <%= f.text_field :name, autofocus: true, class:"input-text form-js-input",placeholder: "とおる" %>
      </div>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="form_line col-6 col-lg-5">
        <%= f.label "Name2" %><br />
        <%= f.text_field :partner_name, autofocus: true, class:"input-text form-js-input",placeholder: "ねね" %>
      </div>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="form_line col-6 col-lg-5">
        <%= f.label "Email" %><br />
        <%= f.email_field :email, autofocus: true, class:"input-text form-js-input",placeholder: "sample@email.com" %>
      </div>
    </div>
    <div class="row mt-5 mb-5 offset-md-8 form_btn">
      <%= f.submit "Update",class:"btn btn-border" %>
    </div>
    <div class="row mt-5 mb-5 offset-md-8">
      <%= link_to "退会",confirm_unsubscribe_path,class:"btn-flat-dashed-border" %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-8 mx-auto">
      <h5 class="mt-5 mt-lg-0 text-center">Users</h5>
      <div class="row mt-3 ml-4 mb-5">
        <%= render 'index', users: @users %>
      </div>
      <%= paginate @users %>
    </div>

    <div class="aniv-user col-md-3 mx-auto">
      <h5 class="mt-5 mt-lg-0 pt-1 text-center">Happy Anniversary</h5>
      <div class="row mt-3">
        <% @ausers.each do |user| %>
          <% unless user.is_deleted == true %>
            <% if user.anniversary.month | user.anniversary.day == Date.today.month | Date.today.day %>
              <div class="col-md-2.5" style="margin-left: 60px;">
                <div class="row mt-3">
                  <div class="col-md-12 text-left">
                    <%= attachment_image_tag(user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg", size: "50x50",class: "rounded-circle")%>
                    <%= link_to user.couple_name,user_path(user.id), 'data-turbolinks': false %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-xs-12 col-lg-8 col-xl-9 mx-auto mb-3">
  <h3 class="mypage-main mt-lg-0 text-center"><%= @user.couple_name %></h3>
</div>

<div class='container px-5 px-sm-0 mb-5 mt-4'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'info', user: @user %>

    <div class='weather mt-4'>
      <div class="weather-main"><h3>Today's Weather</h3></div>

        <input id="cityname" type="text" size="14" maxlength="14" placeholder="Tokyo">
        <button id="btn"><i class="fas fa-search"></i></button><br>
        <span>場所 :</span>
        <span id="place"></span><br>
        <span>最高気温 :</span>
        <span id="temp_max"></span>
        <span> ℃</span><br>
        <span>最低気温 :</span>
        <span id="temp_min"></span>
        <span> ℃</span><br>
        <span>湿度 :</span>
        <span id="humidity"></span>
        <span> %</span><br>
        <span>風速 :</span>
        <span id="speed"></span>
        <span> m/s</span><br>
        <span>天気 :</span>
        <span id="weather"></span>
        <div id="icon"><img id="wimg"></div>
        <script src="jquery.min.js"></script>
        <script src="script.js"></script>
      </div>
    </div>

    <div class="col-md-8">
      <h5 class="mt-5 mt-lg-0 text-center">Posts</h5>
      <div class="row mt-3 mb-5">
        <% @photos.each do |photo| %>
          <div class="col-md-2.5" style="margin-left: 60px;">
            <div class="row mt-3">
              <div class="col-md-12 text-left">
                <%= link_to photo_path(photo.id) do %>
                  <%= attachment_image_tag photo, :image,:fill, 200,150 , 'data-turbolinks': false%>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 text-left" style="margin-top: 20px;">
                <%= photo.title %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= paginate @photos %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class='container mt-3 mb-5'>
  <div class='row'>
    <div class='px-3 mx-auto text-center'>
      
      <div class="unsubscribe-main">
        <h2>本当に退会しますか？</h2>
      </div>
      <div class="unsubscribe-text mt-3">
        <p>
          退会すると、会員登録情報や</br>
          これまでの投稿履歴が閲覧できなくなります。</br>
          退会する場合は、「退会する」をクリックしてください。
        </p>
      </div>
      <div class="unsubscribe-btn mt-5">
        <%= link_to '退会しない', user_path(@user.id),class: "btn-flat-dashed-filled mr-5" %>
        <%= link_to "退会する", withdraw_user_path,class: "btn-flat-dashed-border", method: :patch %>
      </div>

    </div>
  </div>
</div>