config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'search/search'
  devise_for :users
  root 'homes#about'
  get 'top' => 'homes#top'
  get 'user/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'user/withdraw' => 'users#withdraw'
  get '/search' => 'search#search'

  resources :users, only: [:show, :edit, :update, :index, :unsubscribe, :withdraw] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'favorites' => 'favorites#favorites', as: 'favorites'
  end

  resources :photos, only: [:show, :edit, :update, :index, :destroy, :new, :create] do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
>>>>>>> origin/main
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
  validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回お気に入りさせない
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
	belongs_to :photo
	validates_uniqueness_of :photo_id, scope: :user_id #同じ投稿に複数回いいねさせない
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, class_name: 'User'
  attachment :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image,presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
      Photo.where('title LIKE(?) OR body LIKE(?) OR place LIKE(?)', '%'+content+'%', '%'+content+'%', '%'+content+'%')
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationshios, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #自分がフォローされる側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #自分がフォローする側
  has_many :followers, through: :reverse_of_relationshios, source: :follower #自分をフォローしてるユーザー
  has_many :followings, through: :relationships, source: :followed #自分がフォローしてるユーザー

  validates :name, presence: true
  validates :partner_name, presence: true
  validates :couple_name, presence: true
  validates :email, presence: true
  validates :anniversary, presence: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
      User.where('couple_name LIKE ?', '%'+content+'%')
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @photos = Photo.limit(5).order(" created_at DESC ")
    @users = User.limit(5)
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.new(photo_id: @photo.id)
    like.save
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    like = current_user.likes.find_by(photo_id: @photo.id)
    like.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @ausers = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :partner_name, :anniversary, :couple_name, :email, :is_deleted, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h4><%= obj.errors.count %>件のエラーが発生しました。</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container foot">
  <div class="row">
    <div class="mx-auto">
      <footer>asu.inc</footer>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <% if user_signed_in? %>
        <a class="navbar-brand" href="/top"><%= image_tag "logo.png", size:"150" %></a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto d-flex align-items-start">
            <li class="nav-item">
              <%= link_to "", photos_path,class: 'fab fa-fort-awesome nav-link text-danger' %>
            </li>
            <li class="nav-item">
              <%= link_to "", users_path,class: 'fas fa-users nav-link text-danger' %>
            </li>
            <li class="nav-item">
              <%= link_to " ", new_photo_path,class: 'fas fa-plus nav-link text-danger' %>
            </li>
            <li class="nav-item">
              <%= link_to "", user_favorites_path(current_user.id),class: 'far fa-bookmark nav-link text-danger' %>
            </li>
            <li class="nav-item" data-turbolinks='false'>
              <%= link_to "", user_path(current_user.id),class: 'fas fa-globe nav-link text-danger' %>
            </li>
            <li class="search_form">
              <%= form_with url: search_path, method: :get, local: true do |f| %>
                <%= f.text_field :content, class:"search_text" %>
                <%= f.select :model, options_for_select({"User" => "user", "Post" =>"photo"}),{}, {class: 'search_select'} %>
                <button class="search_btn" type="submit"><i class="fas fa-search"></i></button>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div data-turbolinks='false'><a class="navbar-brand" href="/"><%= image_tag "logo.png", size:"150" %></a></div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto d-flex align-items-start">
            <li class="nav-item">
              <%= link_to "Signup",new_user_registration_path,class: 'nav-link text-danger' %>
            </li>
            <li class="nav-item">
              <%= link_to "Login",new_user_session_path,class: 'nav-link text-danger' %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <title>Asu</title>
=======
    <title>Sonia</title>
>>>>>>> origin/main
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<<<<<<< HEAD
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>
=======
  </head>

  <body>
    <%= yield %> 
  </body>
</html>

<!---->
>>>>>>> origin/main